"""Add DomainScreenshot and urlscan fields

Revision ID: 0fdf77e49b52
Revises: 14eefc6896ef
Create Date: 2026-01-30 22:01:38.022290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fdf77e49b52'
down_revision = '14eefc6896ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_screenshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('image_filename', sa.String(length=255), nullable=False),
    sa.Column('urlscan_uuid', sa.String(length=100), nullable=True),
    sa.Column('scan_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['phishing_domain.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('domain_screenshot')
    # ### end Alembic commands ###
