"""Add is_admin to User

Revision ID: 117ab563fc6c
Revises: 2df69c50070a
Create Date: 2026-01-12 21:57:11.360506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '117ab563fc6c'
down_revision = '2df69c50070a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
