"""Add whois_snapshot to PhishingDomain

Revision ID: 14eefc6896ef
Revises: 47cba5d21229
Create Date: 2026-01-30 21:25:07.607945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14eefc6896ef'
down_revision = '47cba5d21229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phishing_domain', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whois_snapshot', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phishing_domain', schema=None) as batch_op:
        batch_op.drop_column('whois_snapshot')

    # ### end Alembic commands ###
