"""Add Shodan enrichment fields

Revision ID: 471235237b52
Revises: f0dc2d8de157
Create Date: 2026-02-28 12:33:05.314148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '471235237b52'
down_revision = 'f0dc2d8de157'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phishing_domain', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shodan_isp', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('shodan_open_ports', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('shodan_cves', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phishing_domain', schema=None) as batch_op:
        batch_op.drop_column('shodan_cves')
        batch_op.drop_column('shodan_open_ports')
        batch_op.drop_column('shodan_isp')

    # ### end Alembic commands ###
