"""Add Evasion models and is_evasive column

Revision ID: 623899ab4187
Revises: 471235237b52
Create Date: 2026-03-02 20:21:54.509229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '623899ab4187'
down_revision = '471235237b52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('path_to_check',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_table('subdomain_to_check',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subdomain', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subdomain')
    )
    with op.batch_alter_table('phishing_domain', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_evasive', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phishing_domain', schema=None) as batch_op:
        batch_op.drop_column('is_evasive')

    op.drop_table('subdomain_to_check')
    op.drop_table('path_to_check')
    # ### end Alembic commands ###
