"""Add urlscan columns to PhishingDomain

Revision ID: 92bf52261e21
Revises: 0fdf77e49b52
Create Date: 2026-01-30 22:02:16.885942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92bf52261e21'
down_revision = '0fdf77e49b52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phishing_domain', schema=None) as batch_op:
        batch_op.add_column(sa.Column('urlscan_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('last_urlscan_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phishing_domain', schema=None) as batch_op:
        batch_op.drop_column('last_urlscan_date')
        batch_op.drop_column('urlscan_status')

    # ### end Alembic commands ###
