"""Add mx_records and ThreatTerm

Revision ID: 9b3451b579bf
Revises: 117ab563fc6c
Create Date: 2026-01-15 00:28:43.587242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b3451b579bf'
down_revision = '117ab563fc6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threat_term',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term')
    )
    with op.batch_alter_table('phishing_domain', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mx_records', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phishing_domain', schema=None) as batch_op:
        batch_op.drop_column('mx_records')

    op.drop_table('threat_term')
    # ### end Alembic commands ###
