"""Add geolocation fields

Revision ID: a3bb45ffd7d4
Revises: a1b2c3d4e5f6
Create Date: 2026-01-31 01:43:50.786505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3bb45ffd7d4'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phishing_domain', schema=None) as batch_op:
        batch_op.add_column(sa.Column('geolocation_iso', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('geolocation_country', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phishing_domain', schema=None) as batch_op:
        batch_op.drop_column('geolocation_country')
        batch_op.drop_column('geolocation_iso')

    # ### end Alembic commands ###
