"""Add ParkingNameserver model

Revision ID: b6f94f9e8d60
Revises: f42a226cbbfe
Create Date: 2026-02-27 22:24:18.011283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6f94f9e8d60'
down_revision = 'f42a226cbbfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parking_nameserver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ns', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ns')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parking_nameserver')
    # ### end Alembic commands ###
