"""Add failed_login_attempts to User

Revision ID: d756b3fed2ca
Revises: 9b3451b579bf
Create Date: 2026-01-15 13:57:34.712789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd756b3fed2ca'
down_revision = '9b3451b579bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('failed_login_attempts')

    # ### end Alembic commands ###
