"""Add Hold Integrity columns

Revision ID: f42a226cbbfe
Revises: a3bb45ffd7d4
Create Date: 2026-02-26 23:15:39.549068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f42a226cbbfe'
down_revision = 'a3bb45ffd7d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phishing_domain', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('hold_integrity_data', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phishing_domain', schema=None) as batch_op:
        batch_op.drop_column('hold_integrity_data')
        batch_op.drop_column('source')

    # ### end Alembic commands ###
