"""Add correlation fields

Revision ID: f474eb8796e5
Revises: d756b3fed2ca
Create Date: 2026-01-17 12:06:08.690405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f474eb8796e5'
down_revision = 'd756b3fed2ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phishing_domain', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asn_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('asn_org', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('favicon_mmh3', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('jarm_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('html_artifacts', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phishing_domain', schema=None) as batch_op:
        batch_op.drop_column('html_artifacts')
        batch_op.drop_column('jarm_hash')
        batch_op.drop_column('favicon_mmh3')
        batch_op.drop_column('asn_org')
        batch_op.drop_column('asn_number')

    # ### end Alembic commands ###
